[package]
name = "nexus-rt-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
proc-macro-crate = "3.1.0"
syn = { version = "1.0", features = ["full"] }
regex = { version = "1.10.6", default-features = false }
jolt-common = { git = "https://github.com/nexus-xyz/jolt", rev = "b653696", package = "common" }
postcard = { version = "1.0.8", features = ["alloc"] }

[dev-dependencies]
trybuild = { version = "1.0.49", features = ["diff"] }

[[test]]
name = "build-tests"
path = "build-tests/compiletest.rs"

[features]
jolt-io = []
