[package]
name = "nexus-rt-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
syn = { version = "1.0", features = ["full"] }
jolt-common = { git = "https://github.com/nexus-xyz/jolt", rev = "f0f1f12", package = "common" }

[dev-dependencies]
trybuild = { version = "1.0.49", features = ["diff"] }

[[test]]
name = "build-tests"
path = "build-tests/compiletest.rs"
